services:
    engine:
        build:
            context: engine
            dockerfile: ../engine.Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./engine:/app
        working_dir: /app
        environment:
            TZ: Asia/Kuala_Lumpur