services:
    frontend:
        image: node:22
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
        working_dir: /app
        env_file:
            - .env
        environment:
            TZ: Asia/Kuala_Lumpur

    engine:
        build:
            context: engine
            dockerfile: ../engine.Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./engine:/app
        working_dir: /app
        env_file:
            - .env
        environment:
            PORT: ${ENGINE_PORT}
            TZ: Asia/Kuala_Lumpur