services:
    frontend:
        extends:
            file: common.yaml
            service: frontend
        environment:
            NODE_ENV: development
        depends_on:
            engine:
                condition: service_healthy
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -d "node_modules" ]
                then
                    npm install
                fi
                npm run dev

    engine:
        extends:
            file: common.yaml
            service: engine
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 1s
            timeout: 5s
            retries: 10
        command:
            - /bin/sh
            - -c
            - |
                deno task dev
