services:
    engine:
        extends:
            file: common.yaml
            service: engine
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 1s
            timeout: 5s
            retries: 10
        command:
            - /bin/sh
            - -c
            - |
                deno task dev
